use_frameworks!

target 'JAPagerViewController_Example' do
  pod 'JAPagerViewController', :path => '../'

  target 'JAPagerViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
