platform :ios, ‘9.0’


use_frameworks!

target 'JAPagerViewController_Example' do
  pod 'JAPagerViewController', :path => '../'

  target 'JAPagerViewController_Tests' do
    inherit! :search_paths
  end
end
